defaults:
  - refold: alphafold3
  - inversefold: gRNAde_rna
  - metrics: nucleotide_metrics

design_dir: ${oc.env:DESIGN_DIR,examples/nuc/rna}
root: results
gpus: 0

hydra:
  job:
    chdir: false
  run:
    dir: ${root}/hydra
