defaults:
  - metrics: protein_binding_ligand

# design_dir: examples/ODesign/protein_binding_ligand/oqo
design_dir: ${oc.env:DESIGN_DIR,examples/ODesign/protein_binding_ligand/oqo}
root: results
gpus: 0

hydra:
  job:
    chdir: false
  run:
    dir: ${root}/hydra
