defaults:
  - refold: alphafold3
  - inversefold: InverseFold
  - metrics: nucleotide_metrics

# design_dir: examples/nuc/rna
design_dir: ${oc.env:DESIGN_DIR,examples/nuc/rna}
root: results
gpus: 2

hydra:
  job:
    chdir: false
  run:
    dir: ${root}/hydra
